export const environment = {
    production: true,
    hmr: false,
    //API:'https://localhost:5001/api/',
    //API_MOCK:'http://localhost:8080/',
    API: 'http://hysdesentope.com/api/',

    clientes: 'Cliente',
  empresas: 'Empresa',
  parceiros: 'Parceiro',
  usuarios: 'Usuario',
  perfilUsuario: 'PerfilUsuario',
  countries: 'Countries',
  currencies: 'Currencies',
  cultures: 'Cultures',
  customerGroup: 'CustomerGroup',
  paymentMethods: 'PaymentMethods',
  paymentTerms: 'PaymentTerms',
  deliveryTerms: 'DeliveryTerms',
  partyTaxSchemas: 'PartyTaxSchemas',
  partyWithholdingTaxSchemas: 'PartyWithholdingTaxSchemas',
  priceLists: 'PriceLists',
  artigoVendas: 'SalesItem',
  unit: 'Unit',
  assortments: 'Assortments',
  brands: 'Brands',
  brandModels: 'BrandModels',
  invoiceTypes: 'InvoiceTypes',
  invoice: 'SalesInvoice',
  series: 'Series',
  warehouses:'Warehouses',
  itemTaxSchemas: 'ItemTaxSchemas',
  itemWithholdingTaxSchemas: 'ItemWithholdingTaxSchemas',
  titulos: 'titulos',
  ambiente: "dsv"
  
};